# constants.py

# Длины полей для модели User
USER_EMAIL_MAX_LENGTH = 254
USER_USERNAME_MAX_LENGTH = 150
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150

# Длины полей для модели Ingredient
INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64

# Длины полей для модели Recipe
RECIPE_NAME_MAX_LENGTH = 256
RECIPE_COOKING_TIME_MIN_VALUE = 1
RECIPE_COOKING_TIME_MAX_VALUE = 10000

# Длины полей для модели RecipeIngredient
RECIPE_INGREDIENT_AMOUNT_MIN_VALUE = 1
RECIPE_INGREDIENT_AMOUNT_MAX_VALUE = 10000

# Пути для загрузки изображений
AVATAR_UPLOAD_PATH = 'avatars/'
RECIPE_IMAGE_UPLOAD_PATH = 'recipes/images/'


MAX_RECIPES_LIMIT = 10**10
